In [1]:
import numpy as np

In [2]:
arr=np.array([0,1,2,3,4])
arr

array([0, 1, 2, 3, 4])

In [3]:
arr[2]=5
arr

array([0, 1, 5, 3, 4])

In [4]:
arr[4]=6
arr

array([0, 1, 5, 3, 6])

In [6]:
arr=np.array([0,1,2,3,4])
arr
for i in range(len(arr)):
    arr[1]=5
    arr[3]=6
    break
arr

array([0, 5, 2, 6, 4])

In [7]:
arr=np.random.randint(1,7,(3,3))
arr

array([[4, 1, 5],
       [4, 6, 6],
       [1, 5, 6]], dtype=int32)