In [3]:
import numpy as np
print("numpy is imported")

numpy is imported


In [5]:
import numpy as np
print("numpy is imported")

numpy is imported


In [ ]:
# NUMPY
#create array
# arrays are faster than list
# list cant be used for larger data asit istime consuming


In [7]:
# creating an array
ls=[41,52,63,96,45,87,69]
ls

[41, 52, 63, 96, 45, 87, 69]

In [6]:
ls=[23,34,45,566,67,78]
ls

[23, 34, 45, 566, 67, 78]

In [7]:
arr=np.array(ls)
arr

array([ 23,  34,  45, 566,  67,  78])

In [19]:
arr=np.array(ls)
arr

array(['41', '52', '63', '96', '45', '87', '69', '12.2', 'upflairs'],
      dtype='<U32')

In [1]:
type(arr)

NameError: name 'arr' is not defined

In [10]:
type(arr)

numpy.ndarray

In [9]:
arr/2

array([ 11.5,  17. ,  22.5, 283. ,  33.5,  39. ])

In [12]:
arr *5000000

array([205000000, 260000000, 315000000, 480000000, 225000000, 435000000,
       345000000])

In [10]:
arr.ndim

1

In [13]:
arr.ndim  # ndim give number of dimension

1

In [14]:
arr.dtype  # show datatype of array

dtype('int64')

In [11]:
arr.dtype

dtype('int64')

In [ ]:
[[],[],[]]  # 2d array

In [17]:
ls=[41,52,63,96,45,87,69,12.2,"upflairs"]
arr=np.array(ls) 
arr

array(['41', '52', '63', '96', '45', '87', '69', '12.2', 'upflairs'],
      dtype='<U32')

In [18]:
arr.dtype

dtype('<U32')

In [ ]:
# array
# collection of data with similar data types
#CONTAGIOUS MEMORY ELEMENTS

In [14]:
ls=[12,23,34,45,56]
arr=np.array(ls)
arr

array([12, 23, 34, 45, 56])

In [4]:
ls=[41,52,63,96,45,87,69]
arr=np.array(ls) 
arr

NameError: name 'np' is not defined

In [15]:
arr[4]

np.int64(56)

In [21]:
arr[2]

np.int64(63)

In [3]:
ls=[41,52,63,67,78,89,56,54,32,43]
arr=np.array(ls)
arr

NameError: name 'np' is not defined

In [16]:
arr[3:4:1]

array([45])

In [27]:
arr[2:5:2]  # access

array([63, 78])

In [17]:
arr.size

5

In [28]:
arr.size

10

In [18]:
len(arr)

5

In [29]:
len(arr)

10

In [1]:
for i in range(len(arr)):
    if arr[i]<50:
       break
print(arr[i])
        

NameError: name 'arr' is not defined

In [19]:
arr[arr>10]

array([12, 23, 34, 45, 56])

In [34]:
arr[arr<50]   # filtering items less then 50

    

array([41, 32, 43])

In [20]:
arr.shape

(5,)

In [36]:
arr.shape # give lengtth of array

(10,)

In [22]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
arr2=np.arange(50)  # always give 1d array
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [26]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones((10,5,2))   # 2D array

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [47]:
np.zeros((10))  # make array of 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [48]:
np.linspace(1,8,5)  #in between 1 to 8 fill 5 items

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [31]:
random.randint(15,50)

27

In [28]:
import random

In [58]:
random.randint(1,10)  # generate random values

10

In [34]:
random.random()

0.7546626608352334

In [60]:
random.random()  # return values between 0 to 1

0.3250251788334583

In [35]:
ls=['arushi','nikita','pragati','yash']
ls

['arushi', 'nikita', 'pragati', 'yash']

In [38]:
random.choice(ls)

'pragati'

In [65]:
random.choice(ls)  # randpmly pick one item

'nikita'

In [43]:
random.choices(ls,k=4)

['yash', 'pragati', 'nikita', 'nikita']

In [67]:
random.choices(ls)  # give one in form of list

['yash']

In [69]:
random.choices(ls,k=2)  # 

['pragati', 'pragati']

In [51]:
ls=['arushi','nikita','pragati','yash']
ls

['arushi', 'nikita', 'pragati', 'yash']

In [52]:
random.shuffle(ls)
ls

['yash', 'nikita', 'pragati', 'arushi']

In [79]:
random.shuffle(ls)

In [80]:
ls

['pragati', 'yash', 'nikita', 'arushi']

In [53]:
np.random.randint(1,50,10)

array([17, 45, 40,  6,  4, 38,  3, 48, 48, 24], dtype=int32)

In [54]:
np.random.randint(1,65,(10,5))

array([[18, 46, 16,  3, 52],
       [51, 56, 64, 47, 37],
       [59, 27, 27,  7, 21],
       [52, 51, 22, 48, 13],
       [10, 32, 10, 54, 23],
       [18, 57, 37, 35, 25],
       [16, 30, 32, 19, 30],
       [ 2,  1, 37, 36, 63],
       [20, 47,  7,  7, 20],
       [16, 18, 19, 38, 40]], dtype=int32)

In [87]:
np.random.randint(1,50,(10,5))

array([[ 6, 43, 19, 31, 14],
       [10, 31, 48, 15, 28],
       [26, 13, 45, 39, 42],
       [42, 42, 23, 23, 28],
       [11, 18, 24, 33,  8],
       [40, 45,  2, 34,  5],
       [49, 24, 19,  3, 13],
       [ 7, 31,  8, 47, 33],
       [20,  4, 16, 22, 38],
       [43, 28, 18, 40, 42]], dtype=int32)

In [89]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [56]:
arr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
arr.reshape(15,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [58]:
arr2=np.resize(arr,(25,25))
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,
         4,  5,  6,  7,  8,  9, 10, 11,  0],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
         5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11,  0,  1,  2],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,
         8,  9, 10, 11,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,
         9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 

In [97]:
arr2=np.resize(arr,(25,25))
arr2# if items are less then it add items from array only

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [59]:
arr2.shape

(25, 25)

In [98]:
arr2.shape

(25, 25)

In [99]:
arr2.ndim

2

In [62]:
arr2.reshape(625,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,
        1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
        0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9

In [100]:
#reshape 1---> 2d

#vice versa possible
arr2.reshape(625,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [63]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,
        3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,
        1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
        0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9

In [101]:
arr2.ravel()  # convert any dimension array in 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [102]:
arr2.flatten()  # same as ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [1]:
import numpy as np

In [3]:
arr=np.random.randint(5,50,100)
arr

array([30, 34, 29, 48, 17, 15, 26,  6, 30, 35,  5, 22, 40, 17,  7, 23, 27,
       28, 14, 30, 25,  5, 47, 40, 37, 17, 24, 34, 41, 34, 19,  5, 44, 14,
       14, 36, 47,  7,  7, 32, 36, 15, 44, 12,  8, 19, 40, 40, 23, 31,  5,
       21, 48, 44, 17, 33, 28, 27, 35, 48, 44, 16, 21, 47, 38, 11, 13, 31,
       27, 11, 46, 35, 30, 21, 46, 46, 20, 38,  6, 30, 24, 21, 48, 37, 28,
       12,  8, 27, 43, 40, 35, 40, 21, 13,  6,  7, 25, 25, 44,  9],
      dtype=int32)

In [5]:
arr.min() # max


np.int32(5)

In [6]:
arr.sum()

np.int64(2676)

In [7]:
arr.mean()

np.float64(26.76)

In [9]:
arr=np.random.randint(5,50,(4,3))
arr

array([[14, 32, 35],
       [19, 43, 21],
       [14, 18, 21],
       [20, 45, 21]], dtype=int32)

In [10]:
arr.shape

(4, 3)

In [12]:
np.transpose(arr).shape

(3, 4)

In [13]:
arr.T  # same as transpose

array([[14, 19, 14, 20],
       [32, 43, 18, 45],
       [35, 21, 21, 21]], dtype=int32)

In [27]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 3,  3, 11, 11,  2],
       [ 6,  3,  4,  8,  2],
       [ 3,  9, 10,  3,  2],
       [ 5,  2,  7,  6,  2],
       [ 7,  8,  6,  8,  7],
       [10,  4, 10,  4, 11],
       [ 5,  7,  3,  6,  7],
       [ 5,  9,  8,  8,  3],
       [ 7, 10,  9,  8,  2],
       [ 6,  5, 10,  9,  2]], dtype=int32)

In [18]:
import random

In [29]:
arr.ravel()

array([ 3,  3, 11, 11,  2,  6,  3,  4,  8,  2,  3,  9, 10,  3,  2,  5,  2,
        7,  6,  2,  7,  8,  6,  8,  7, 10,  4, 10,  4, 11,  5,  7,  3,  6,
        7,  5,  9,  8,  8,  3,  7, 10,  9,  8,  2,  6,  5, 10,  9,  2],
      dtype=int32)

In [36]:
np.reshape(arr,25)

ValueError: cannot reshape array of size 50 into shape (25,)

In [37]:
arr

array([[ 3,  3, 11, 11,  2],
       [ 6,  3,  4,  8,  2],
       [ 3,  9, 10,  3,  2],
       [ 5,  2,  7,  6,  2],
       [ 7,  8,  6,  8,  7],
       [10,  4, 10,  4, 11],
       [ 5,  7,  3,  6,  7],
       [ 5,  9,  8,  8,  3],
       [ 7, 10,  9,  8,  2],
       [ 6,  5, 10,  9,  2]], dtype=int32)

In [39]:
#arr[R][C]
arr[-1]

array([ 6,  5, 10,  9,  2], dtype=int32)

In [42]:
arr[7:]  # arr[7:10]

array([[ 5,  9,  8,  8,  3],
       [ 7, 10,  9,  8,  2],
       [ 6,  5, 10,  9,  2]], dtype=int32)

In [46]:
arr[0:10]

array([[ 3,  3, 11, 11,  2],
       [ 6,  3,  4,  8,  2],
       [ 3,  9, 10,  3,  2],
       [ 5,  2,  7,  6,  2],
       [ 7,  8,  6,  8,  7],
       [10,  4, 10,  4, 11],
       [ 5,  7,  3,  6,  7],
       [ 5,  9,  8,  8,  3],
       [ 7, 10,  9,  8,  2],
       [ 6,  5, 10,  9,  2]], dtype=int32)

In [47]:
arr[-10:,-5:-3]

array([[ 3,  3],
       [ 6,  3],
       [ 3,  9],
       [ 5,  2],
       [ 7,  8],
       [10,  4],
       [ 5,  7],
       [ 5,  9],
       [ 7, 10],
       [ 6,  5]], dtype=int32)

In [51]:
arr[-7:-4,-3:]

array([[ 7,  6,  2],
       [ 6,  8,  7],
       [10,  4, 11]], dtype=int32)

In [50]:
arr[3:6,2:]

array([[ 7,  6,  2],
       [ 6,  8,  7],
       [10,  4, 11]], dtype=int32)

In [52]:
arr[0:9:2,2:]

array([[11, 11,  2],
       [10,  3,  2],
       [ 6,  8,  7],
       [ 3,  6,  7],
       [ 9,  8,  2]], dtype=int32)

In [54]:
arr[-8::2,-3]

array([10,  6,  3,  9], dtype=int32)

In [ ]:
arr[0:,0:2]
Sarika Jain
5:11 PM
[0: , :2]
Kartik Jangir
5:12 PM
print(arr3[:10,:2])
Neha Saini
5:12 PM
arr[:10,:2]
Ayushi Jain
5:13 PM
Arr[-10:,-5:-3]
Ronak Bedi
5:13 PM
print(arr[-10:,:-3])

In [2]:
import numpy as np

In [3]:
arr=np.random.randint(2,30,(10,5,5))
arr

array([[[27,  9,  8,  2, 17],
        [ 9,  9,  8,  3, 27],
        [12, 10, 22, 18, 25],
        [19, 10, 25, 25, 10],
        [12, 10,  9,  3, 20]],

       [[ 8,  8,  8, 23, 14],
        [23,  7, 12, 29, 15],
        [11, 14, 21, 16, 29],
        [26, 27, 26, 16,  2],
        [11, 17, 15,  3, 26]],

       [[ 5, 27, 16, 17,  2],
        [27, 29,  2, 12, 14],
        [11, 14, 21, 18, 10],
        [11,  9,  2, 14, 18],
        [25, 28,  2, 13, 12]],

       [[12, 28,  7, 16, 26],
        [24, 18, 24, 23, 21],
        [15, 26, 23, 27, 10],
        [ 9, 14, 27,  4, 12],
        [12,  4, 19, 26, 14]],

       [[10, 11, 14,  3, 11],
        [ 6, 17, 15, 11, 13],
        [ 8, 27, 27, 25, 17],
        [27,  8, 18, 22,  7],
        [20,  6,  5, 28, 13]],

       [[22, 27,  8, 26, 22],
        [18, 22, 29,  2, 23],
        [20,  4,  2,  3, 27],
        [27,  2, 29, 20, 29],
        [10,  6, 22, 18,  7]],

       [[ 6, 14,  6, 13, 11],
        [ 7,  6, 15, 18,  5],
        [19, 23, 16, 22,  3]

In [7]:
arr[0,0::2,0:3:2]

array([[27,  8],
       [12, 22],
       [12,  9]], dtype=int32)

In [5]:
arr.shape

(10, 5, 5)

In [15]:
arr=np.random.randint(2,50,(5,5,10))
arr

NameError: name 'np' is not defined

In [58]:
arr=np.random.randint(2,50,(5,10,5))
arr

array([[[43, 18, 11, 35, 44],
        [15, 46, 45, 49,  8],
        [24, 47, 27, 39,  4],
        [ 2, 19, 32, 18, 19],
        [10, 29, 14, 49, 38],
        [23, 24,  4, 23, 48],
        [19, 16,  6, 47, 27],
        [49, 45,  7,  3, 47],
        [39,  2,  7, 43, 10],
        [ 6, 48, 18, 21, 20]],

       [[16, 32,  3, 34, 31],
        [43, 22, 26, 41, 11],
        [13, 16, 44,  4, 34],
        [ 8,  3,  7, 10, 41],
        [20, 46, 12, 27,  8],
        [ 5, 46, 37, 27, 32],
        [ 7, 43, 43, 22,  2],
        [17,  9, 28, 43, 41],
        [ 4, 25, 23, 19, 42],
        [19, 36, 18, 49, 10]],

       [[ 5, 36, 23, 42,  4],
        [ 4, 12,  2, 44, 14],
        [13,  9,  5, 46, 29],
        [19, 10, 14,  4, 34],
        [ 7, 23, 32,  9, 45],
        [45, 30, 46, 25, 39],
        [15,  2, 17, 47,  3],
        [29, 48, 26, 14, 29],
        [44, 12, 32,  4, 41],
        [23,  5, 34, 15, 19]],

       [[39, 19, 47, 10, 22],
        [37, 34, 26, 35,  4],
        [14, 30, 36, 23, 42],
    

In [57]:
arr.shape
#t #R #C

(5, 15, 5)

In [59]:
arr.ndim

3

In [60]:
arr[0]  # output= table of given position

array([[43, 18, 11, 35, 44],
       [15, 46, 45, 49,  8],
       [24, 47, 27, 39,  4],
       [ 2, 19, 32, 18, 19],
       [10, 29, 14, 49, 38],
       [23, 24,  4, 23, 48],
       [19, 16,  6, 47, 27],
       [49, 45,  7,  3, 47],
       [39,  2,  7, 43, 10],
       [ 6, 48, 18, 21, 20]], dtype=int32)

In [61]:
arr[1][7:,0:4]

array([[17,  9, 28, 43],
       [ 4, 25, 23, 19],
       [19, 36, 18, 49]], dtype=int32)

In [63]:
arr[0:4,9,]

array([[ 6, 48, 18, 21, 20],
       [19, 36, 18, 49, 10],
       [23,  5, 34, 15, 19],
       [16, 17, 28, 42,  4]], dtype=int32)

In [65]:
arr=np.array([5,6,7,])
arr

array([5, 6, 7])

In [8]:
arr=np.array([2,41,3,56,12])
arr

array([ 2, 41,  3, 56, 12])

In [15]:
arr.argsort()


array([0, 1, 2, 3, 4])

In [10]:
arr.argmax()

np.int64(3)

In [66]:
arr.max()

np.int64(7)

In [67]:
arr.argmax()  # returns maximum items index

np.int64(2)

In [68]:
arr.argmin()  # minimum item index

np.int64(0)

In [76]:
arr=np.array([23,54,1,2])
arr

array([23, 54,  1,  2])

In [75]:
arr.sort()
arr

array([ 1,  2, 23, 54])

In [77]:
arr

array([23, 54,  1,  2])

In [17]:
np.unique(arr)

array([ 2,  3, 12, 41, 56])

In [78]:
arr.argsort()  #  1,2,23,54 written index for sorting

array([2, 3, 0, 1])

In [79]:
arr

array([23, 54,  1,  2])

In [80]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 2,  9,  4,  7, 11],
       [ 7,  3,  7,  2,  8],
       [ 7, 11,  9, 10,  7],
       [ 4,  7,  4,  3,  8],
       [10,  8,  5,  5, 11],
       [ 8,  3, 10,  8,  9],
       [ 2,  2,  2, 11,  3],
       [ 9,  3,  6,  5,  7],
       [ 3,  5,  8,  2,  9],
       [ 2, 10, 11, 10,  8]], dtype=int32)

In [21]:
import numpy as np

In [24]:
arr[0:1,0:1,0:5,0:2]

array([[[[36, 36],
         [44, 10],
         [34, 45],
         [41, 19],
         [33, 44]]]], dtype=int32)

In [23]:
arr=np.random.randint(2,50,(3,5,5,10))
arr

array([[[[36, 36, 40, 16, 42, 42, 45, 22,  7, 17],
         [44, 10, 45,  8, 47, 45, 29,  4, 26, 11],
         [34, 45, 32,  9, 16, 10, 16, 39, 15,  4],
         [41, 19,  3, 19, 36, 16, 19, 40, 27, 32],
         [33, 44, 42, 32, 42, 32,  3,  7, 45, 43]],

        [[34, 10,  5, 15, 20, 46, 23, 11,  8,  7],
         [ 5,  4, 16, 23, 11, 24,  5, 16, 12, 49],
         [49, 44,  9, 49, 39, 38, 41, 45, 43,  3],
         [17, 48, 43, 49, 38, 46, 45, 20,  9,  8],
         [21, 25, 27, 32, 16, 44, 30,  2, 23, 37]],

        [[16,  8, 39, 21,  8,  6, 37, 32,  4, 29],
         [ 4, 30, 40, 38, 36,  7, 49, 42, 39, 24],
         [14, 12, 11, 46,  8, 11, 24,  9,  4, 18],
         [25, 26, 16, 29, 46, 33,  3, 30, 27, 16],
         [45, 45, 46, 24, 30,  9, 38, 31, 40, 20]],

        [[48,  4, 42, 26, 39, 20, 43, 17, 25, 17],
         [33, 32,  4, 37, 42, 22, 27, 34, 42, 36],
         [47, 33, 42,  8, 35, 40, 29, 16, 35, 32],
         [49, 14,  7,  5, 19, 25, 20, 41,  6, 32],
         [ 9, 17,  4,  9,

In [81]:
np.unique(arr)  # giive items which are unique

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [83]:
arr.mean()

np.float64(6.5)

In [84]:
arr=np.random.randint(2,250,200)
arr

array([194,   2, 248,  13, 160,  35,  38, 114, 211, 244, 245,  15, 143,
        98, 143, 247, 150, 237,  45, 122,  92, 110, 226,   5, 125, 184,
        26, 241,  16,  67, 150, 228, 172,   2,  91, 249,  25, 194,  72,
        52, 173,  13, 228, 185, 227, 220, 111, 160, 194, 150, 133,  21,
        69, 184, 130, 232, 138, 157,  19,  51, 117, 178, 151, 187, 104,
       124, 222, 124,  58, 118, 181, 100, 228,   6,  11, 180, 157, 199,
        77,  14, 201, 191,  30, 144,  86,  53, 224, 185, 246,  51, 233,
       112,  54, 166,  27, 120,   8, 154,  37,   4, 196,  95, 203, 246,
       236, 121,  80,   5, 249, 194, 135, 191, 136,  96, 237,  18,   9,
       203, 213,  85, 129, 195, 227, 101,  19, 117, 140,  29, 185, 234,
       153, 198,  51,  15,  56,  62, 226,   6,  60, 159,  86,   7, 103,
       113, 212,  85, 127,  69, 120, 158, 221, 249, 149, 154, 132, 228,
       198, 124, 249,  32,  43, 200, 111, 205, 187, 210,   4,  40, 193,
       249, 128, 222,  91, 185,  33, 179, 158, 209, 220, 200, 10

In [85]:
np.median(arr)

np.float64(134.0)

In [86]:
arr.var()

np.float64(5756.839599999999)

In [87]:
np.sqrt(25)

np.float64(5.0)

In [31]:
import numpy as np

In [32]:
arr=np.random.randint(2,50,(2,3,6,5))
arr

array([[[[ 2, 10, 35, 44, 31],
         [10, 45, 20, 47,  3],
         [26, 36, 18,  6, 39],
         [38, 32, 38, 41, 44],
         [27, 17, 23, 39, 19],
         [36, 21, 39,  6,  4]],

        [[16, 29, 11, 45, 30],
         [49, 26, 17,  9,  5],
         [48, 27, 44, 36, 17],
         [31, 10,  5, 35, 32],
         [10,  4, 22, 26,  3],
         [ 4, 22, 44, 37, 25]],

        [[36, 30, 29, 31, 39],
         [23, 23, 18, 31, 48],
         [ 7, 38, 26,  4, 16],
         [45, 30, 13, 32,  5],
         [ 9,  5, 40, 12, 45],
         [46, 30, 23, 18, 43]]],


       [[[47, 28, 34, 46, 32],
         [17, 30, 48, 37, 39],
         [31, 29, 29, 40, 29],
         [28,  3,  9, 10, 15],
         [12, 49, 14, 48,  8],
         [11, 29,  7, 10, 31]],

        [[12, 11,  5, 40, 26],
         [12, 44, 17, 34, 20],
         [19, 44, 25, 49, 36],
         [ 6, 37, 42, 21, 31],
         [ 9, 38, 29, 17, 18],
         [20, 45, 40, 33, 13]],

        [[17, 44,  6,  2, 41],
         [44, 12, 48, 11, 1

In [ ]:
# pandas
#pip install pandas

In [88]:
import pandas as pd
print("imported")

imported


In [ ]:
#pandas
# data 3 types
#structural,unstructural,semi structural
# structural data -easy to search,filter,understand,organised well format,data in row,tAble,columns form.
# pandas deal with structured data
#SQL,excel data,csvfile
#pandas enable us to deal with different-different platform structure datas

In [ ]:
# SERIES =1D Array
# dataframe=table
# pandas after reading data give it in form of dataframe


In [ ]:
st=input("enter the value of string")
jewel=input("enter the jewels")
jewel_count=0
for i in range(len(st)):
    if st==jewel:
        jewel_count+=1
print(jewel_count)

In [16]:
st="Abcdef"
jewel="Acf"
jewel_count=0
for i in range(len(st)):
    for j in range(len(jewel)):
        if st[i]==jewel[j]:
           jewel_count+=1
print(jewel_count)

3


In [17]:
#camelcase matching
st="AsDFert"
st.isupper()
print(st.isupper())

False


In [25]:
# ANAGRAM
str="code"
str2="deco"
flag=0
if len(str)==len(str2):
    for i in range(0,len(str)):
        if str[i] not in str2:
            flag=1
            print('False')
            break
        #else:
            #continue
    
    if flag==1:
        print('False')
    else:
        print('True')
    
else:
    print('False')
            
            
            
#print("the given strings are anagram")

True


In [29]:
str=input("enter yr  first string")
str2=input("enter 2nd string")
flag=0
if len(str)==len(str2):
    for i in range(len(str2)):
        if str[i] in str2:
            flag=1

   
    if flag==1:
        print('True')
    else:
        print('False')
else:
    print('False')




True


In [ ]:
# shifting of letters
str=input("enter your string")
shift=int(input("enter how much you want to shift"))



In [35]:
# palindrome of two strings
#ATTAATTA
str="ATTAATTA"


['', 'TT', '', 'TT', '']

In [2]:
import numpy as np

In [3]:
arr=np.array([0,1,2,3,4])
arr

array([0, 1, 2, 3, 4])

In [6]:
arr[2]=5
arr

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed